/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetofastfood.unip;

/**
 *
 * @author mafec
 */
public class TelaConfirmarPedido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaConfirmarPedido.class.getName());

    /**
     * Creates new form TelaConfirmarPedido
     */
    public TelaConfirmarPedido() {
        initComponents();
        
        setSize(900, 700);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblImgFinalizarPedido = new javax.swing.JLabel();
        panelFacaPedido = new javax.swing.JPanel();
        lblFacaPedido = new javax.swing.JLabel();
        lblTextSegundFacaPedido = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblFooter = new javax.swing.JLabel();
        panelEntrega = new javax.swing.JPanel();
        panelTextEntrega = new javax.swing.JPanel();
        lblTextDadosEntrega = new javax.swing.JLabel();
        lblNomeCompleto = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        lblFormaEntrega = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtFormaEntrega = new javax.swing.JTextField();
        spinnerFormaEntrega = new javax.swing.JSpinner();
        lblObservacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaObservacao = new javax.swing.JTextArea();
        panelFormaPagamento = new javax.swing.JPanel();
        panelTextPagamento = new javax.swing.JPanel();
        lblTextFormaPagamento = new javax.swing.JLabel();
        radiobtnPix = new javax.swing.JRadioButton();
        radiobtnCartaoC = new javax.swing.JRadioButton();
        radiobtnCartaoD = new javax.swing.JRadioButton();
        radiobtnDinheiro = new javax.swing.JRadioButton();
        btnVoltaPedido = new javax.swing.JButton();
        btnConfirmarPedido = new javax.swing.JButton();
        btnLimpaDados = new javax.swing.JButton();
        panelResPedido = new javax.swing.JPanel();
        panelTextResPedido = new javax.swing.JPanel();
        lblResPedido = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblValorSubtotal = new javax.swing.JLabel();
        lblTextTaxaEntrega = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblValorTaxa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblRevisePedido = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 241, 214));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(747, 126));

        lblLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\mafec\\Downloads\\LogoBitBurguer (1) (1).png")); // NOI18N

        lblImgFinalizarPedido.setText("FINALIZAR PEDIDO");

        panelFacaPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelFacaPedido.setPreferredSize(new java.awt.Dimension(173, 91));

        lblFacaPedido.setText("FAÇA SEU PEDIDO");

        lblTextSegundFacaPedido.setText("Rápido, fácil e do seu jeito");

        javax.swing.GroupLayout panelFacaPedidoLayout = new javax.swing.GroupLayout(panelFacaPedido);
        panelFacaPedido.setLayout(panelFacaPedidoLayout);
        panelFacaPedidoLayout.setHorizontalGroup(
            panelFacaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacaPedidoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblFacaPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFacaPedidoLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblTextSegundFacaPedido)
                .addContainerGap())
        );
        panelFacaPedidoLayout.setVerticalGroup(
            panelFacaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacaPedidoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblFacaPedido)
                .addGap(18, 18, 18)
                .addComponent(lblTextSegundFacaPedido)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblLogo)
                .addGap(122, 122, 122)
                .addComponent(lblImgFinalizarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(panelFacaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblLogo)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panelFacaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImgFinalizarPedido)
                        .addGap(50, 50, 50))))
        );

        jPanel2.setBackground(new java.awt.Color(181, 18, 23));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(776, 62));

        lblFooter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFooter.setForeground(new java.awt.Color(255, 255, 255));
        lblFooter.setText("BIT BURGUER - FEITO COM QUALIDADE - DO JEITO AMERICANO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFooter)
                .addGap(201, 201, 201))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFooter)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelEntrega.setBackground(new java.awt.Color(255, 241, 214));
        panelEntrega.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEntrega.setPreferredSize(new java.awt.Dimension(603, 350));

        panelTextEntrega.setBackground(new java.awt.Color(181, 18, 23));
        panelTextEntrega.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTextDadosEntrega.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTextDadosEntrega.setForeground(new java.awt.Color(255, 255, 255));
        lblTextDadosEntrega.setText("DADOS DE ENTREGA");

        javax.swing.GroupLayout panelTextEntregaLayout = new javax.swing.GroupLayout(panelTextEntrega);
        panelTextEntrega.setLayout(panelTextEntregaLayout);
        panelTextEntregaLayout.setHorizontalGroup(
            panelTextEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextEntregaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTextDadosEntrega)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTextEntregaLayout.setVerticalGroup(
            panelTextEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextEntregaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextDadosEntrega)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNomeCompleto.setText("Nome Completo:");

        lblTelefone.setText("Telefone:");

        lblEndereco.setText("Endereço:");

        lblFormaEntrega.setText("Forma de Entrega:");

        javax.swing.GroupLayout panelEntregaLayout = new javax.swing.GroupLayout(panelEntrega);
        panelEntrega.setLayout(panelEntregaLayout);
        panelEntregaLayout.setHorizontalGroup(
            panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTextEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelEntregaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefone)
                    .addComponent(lblNomeCompleto)
                    .addComponent(lblEndereco)
                    .addComponent(lblFormaEntrega))
                .addGap(40, 40, 40)
                .addGroup(panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                        .addComponent(txtTelefone)
                        .addComponent(txtNome))
                    .addGroup(panelEntregaLayout.createSequentialGroup()
                        .addComponent(txtFormaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerFormaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEntregaLayout.setVerticalGroup(
            panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntregaLayout.createSequentialGroup()
                .addComponent(panelTextEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCompleto)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone))
                .addGap(18, 18, 18)
                .addGroup(panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaEntrega)
                    .addComponent(txtFormaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerFormaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblObservacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblObservacao.setText("Observação (opcional) :");

        textAreaObservacao.setColumns(20);
        textAreaObservacao.setRows(5);
        jScrollPane1.setViewportView(textAreaObservacao);

        panelFormaPagamento.setBackground(new java.awt.Color(255, 241, 214));
        panelFormaPagamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelTextPagamento.setBackground(new java.awt.Color(181, 18, 23));
        panelTextPagamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTextFormaPagamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTextFormaPagamento.setForeground(new java.awt.Color(255, 255, 255));
        lblTextFormaPagamento.setText("FORMA DE PAGAMENTO");

        javax.swing.GroupLayout panelTextPagamentoLayout = new javax.swing.GroupLayout(panelTextPagamento);
        panelTextPagamento.setLayout(panelTextPagamentoLayout);
        panelTextPagamentoLayout.setHorizontalGroup(
            panelTextPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextPagamentoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTextFormaPagamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTextPagamentoLayout.setVerticalGroup(
            panelTextPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextFormaPagamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        radiobtnPix.setText("VIA PIX");

        radiobtnCartaoC.setText("CARTÃO DE CRÉDITO");

        radiobtnCartaoD.setText("CARTÃO DE DÉBITO");

        radiobtnDinheiro.setText("DINHEIRO");

        javax.swing.GroupLayout panelFormaPagamentoLayout = new javax.swing.GroupLayout(panelFormaPagamento);
        panelFormaPagamento.setLayout(panelFormaPagamentoLayout);
        panelFormaPagamentoLayout.setHorizontalGroup(
            panelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTextPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFormaPagamentoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(radiobtnPix, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiobtnCartaoC)
                .addGap(37, 37, 37)
                .addComponent(radiobtnCartaoD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(radiobtnDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        panelFormaPagamentoLayout.setVerticalGroup(
            panelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormaPagamentoLayout.createSequentialGroup()
                .addComponent(panelTextPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiobtnPix)
                    .addComponent(radiobtnCartaoC)
                    .addComponent(radiobtnCartaoD)
                    .addComponent(radiobtnDinheiro))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnVoltaPedido.setBackground(new java.awt.Color(255, 248, 232));
        btnVoltaPedido.setText("VOLTAR AO PEDIDO");
        btnVoltaPedido.addActionListener(this::btnVoltaPedidoActionPerformed);

        btnConfirmarPedido.setBackground(new java.awt.Color(181, 18, 23));
        btnConfirmarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarPedido.setText("CONFIRMAR PEDIDO");
        btnConfirmarPedido.addActionListener(this::btnConfirmarPedidoActionPerformed);

        btnLimpaDados.setBackground(new java.awt.Color(255, 248, 232));
        btnLimpaDados.setText("LIMPAR DADOS");
        btnLimpaDados.addActionListener(this::btnLimpaDadosActionPerformed);

        panelResPedido.setBackground(new java.awt.Color(255, 241, 214));
        panelResPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelTextResPedido.setBackground(new java.awt.Color(181, 18, 23));
        panelTextResPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblResPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblResPedido.setForeground(new java.awt.Color(255, 255, 255));
        lblResPedido.setText("RESUMO DO PEDIDO");

        javax.swing.GroupLayout panelTextResPedidoLayout = new javax.swing.GroupLayout(panelTextResPedido);
        panelTextResPedido.setLayout(panelTextResPedidoLayout);
        panelTextResPedidoLayout.setHorizontalGroup(
            panelTextResPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTextResPedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResPedido)
                .addGap(23, 23, 23))
        );
        panelTextResPedidoLayout.setVerticalGroup(
            panelTextResPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextResPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSubtotal.setText("Subtotal:");

        lblTextTaxaEntrega.setText("Taxa de entrega:");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal.setText("Total:");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblRevisePedido.setText("Revise seu pedido");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblRevisePedido, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lblRevisePedido)
                .addGap(29, 29, 29))
        );

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblValorTotal.setForeground(new java.awt.Color(181, 18, 23));
        lblValorTotal.setText("R$ 98,00");

        javax.swing.GroupLayout panelResPedidoLayout = new javax.swing.GroupLayout(panelResPedido);
        panelResPedido.setLayout(panelResPedidoLayout);
        panelResPedidoLayout.setHorizontalGroup(
            panelResPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTextResPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelResPedidoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelResPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResPedidoLayout.createSequentialGroup()
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblValorTotal))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResPedidoLayout.createSequentialGroup()
                        .addGroup(panelResPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtotal)
                            .addComponent(lblTextTaxaEntrega))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelResPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblValorSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblValorTaxa, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
            .addGroup(panelResPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResPedidoLayout.createSequentialGroup()
                    .addContainerGap(140, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(7, 7, 7)))
        );
        panelResPedidoLayout.setVerticalGroup(
            panelResPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResPedidoLayout.createSequentialGroup()
                .addComponent(panelTextResPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelResPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValorSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelResPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextTaxaEntrega)
                    .addComponent(lblValorTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelResPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResPedidoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResPedidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(lblValorTotal)
                        .addGap(30, 30, 30)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelResPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelResPedidoLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                    .addGap(218, 218, 218)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblObservacao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panelEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                                    .addComponent(panelFormaPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(panelResPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltaPedido)
                .addGap(71, 71, 71)
                .addComponent(btnLimpaDados)
                .addGap(71, 71, 71)
                .addComponent(btnConfirmarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelResPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblObservacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltaPedidoActionPerformed

    private void btnConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarPedidoActionPerformed

    private void btnLimpaDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpaDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaConfirmarPedido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarPedido;
    private javax.swing.JButton btnLimpaDados;
    private javax.swing.JButton btnVoltaPedido;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFacaPedido;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblFormaEntrega;
    private javax.swing.JLabel lblImgFinalizarPedido;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JLabel lblResPedido;
    private javax.swing.JLabel lblRevisePedido;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTextDadosEntrega;
    private javax.swing.JLabel lblTextFormaPagamento;
    private javax.swing.JLabel lblTextSegundFacaPedido;
    private javax.swing.JLabel lblTextTaxaEntrega;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValorSubtotal;
    private javax.swing.JLabel lblValorTaxa;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel panelEntrega;
    private javax.swing.JPanel panelFacaPedido;
    private javax.swing.JPanel panelFormaPagamento;
    private javax.swing.JPanel panelResPedido;
    private javax.swing.JPanel panelTextEntrega;
    private javax.swing.JPanel panelTextPagamento;
    private javax.swing.JPanel panelTextResPedido;
    private javax.swing.JRadioButton radiobtnCartaoC;
    private javax.swing.JRadioButton radiobtnCartaoD;
    private javax.swing.JRadioButton radiobtnDinheiro;
    private javax.swing.JRadioButton radiobtnPix;
    private javax.swing.JSpinner spinnerFormaEntrega;
    private javax.swing.JTextArea textAreaObservacao;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFormaEntrega;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
