/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetofastfood.unip;

/**
 *
 * @author mafec
 */
public class TelaCardapio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCardapio.class.getName());

    /**
     * Creates new form TelaCardapio
     */
    public TelaCardapio() {
        initComponents();
        
        setSize(900, 700);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        panelCategoriaProdutos = new javax.swing.JPanel();
        panelCategoriaTitulo = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        btnHamburguer = new javax.swing.JButton();
        btnBatatas = new javax.swing.JButton();
        btnCombos = new javax.swing.JButton();
        btnNuggets = new javax.swing.JButton();
        btnMilkShakes = new javax.swing.JButton();
        btnBebidas = new javax.swing.JButton();
        panelFooter = new javax.swing.JPanel();
        lblFooter = new javax.swing.JLabel();
        btnLimparPedido = new javax.swing.JButton();
        panelInfoProdutos = new javax.swing.JPanel();
        panelEscolhaInfo = new javax.swing.JPanel();
        lblEscolha = new javax.swing.JLabel();
        lblTipoCategoria = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        comboBoxProdutos = new javax.swing.JComboBox<>();
        lblPreco = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textaAreaDescProduto = new javax.swing.JTextArea();
        lblQuantidade = new javax.swing.JLabel();
        spinerQuantidade = new javax.swing.JSpinner();
        txtQuantidade = new javax.swing.JTextField();
        btnAddPedido = new javax.swing.JButton();
        btnMeuPedido = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblValorDoProduto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 241, 214));

        panelHeader.setBackground(new java.awt.Color(255, 241, 214));
        panelHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\mafec\\Downloads\\LogoBitBurguer (1) (1).png")); // NOI18N

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCategoriaProdutos.setBackground(new java.awt.Color(255, 241, 214));
        panelCategoriaProdutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelCategoriaTitulo.setBackground(new java.awt.Color(0, 0, 0));
        panelCategoriaTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCategoriaTitulo.setForeground(new java.awt.Color(255, 255, 255));

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("CATEGORIAS");

        javax.swing.GroupLayout panelCategoriaTituloLayout = new javax.swing.GroupLayout(panelCategoriaTitulo);
        panelCategoriaTitulo.setLayout(panelCategoriaTituloLayout);
        panelCategoriaTituloLayout.setHorizontalGroup(
            panelCategoriaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCategoriaTituloLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(lblCategoria)
                .addGap(60, 60, 60))
        );
        panelCategoriaTituloLayout.setVerticalGroup(
            panelCategoriaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCategoriaTituloLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(lblCategoria)
                .addContainerGap())
        );

        btnHamburguer.setBackground(new java.awt.Color(181, 18, 23));
        btnHamburguer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHamburguer.setText("HAMBÚRGUERES");
        btnHamburguer.addActionListener(this::btnHamburguerActionPerformed);

        btnBatatas.setBackground(new java.awt.Color(255, 248, 232));
        btnBatatas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBatatas.setText("BATATAS");
        btnBatatas.addActionListener(this::btnBatatasActionPerformed);

        btnCombos.setBackground(new java.awt.Color(255, 248, 232));
        btnCombos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCombos.setText("COMBOS");

        btnNuggets.setBackground(new java.awt.Color(255, 248, 232));
        btnNuggets.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuggets.setText("NUGGETS");
        btnNuggets.addActionListener(this::btnNuggetsActionPerformed);

        btnMilkShakes.setBackground(new java.awt.Color(255, 248, 232));
        btnMilkShakes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMilkShakes.setText("MILKSHAKES");
        btnMilkShakes.addActionListener(this::btnMilkShakesActionPerformed);

        btnBebidas.setBackground(new java.awt.Color(255, 248, 232));
        btnBebidas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBebidas.setText("BEBIDAS");
        btnBebidas.addActionListener(this::btnBebidasActionPerformed);

        javax.swing.GroupLayout panelCategoriaProdutosLayout = new javax.swing.GroupLayout(panelCategoriaProdutos);
        panelCategoriaProdutos.setLayout(panelCategoriaProdutosLayout);
        panelCategoriaProdutosLayout.setHorizontalGroup(
            panelCategoriaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCategoriaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCategoriaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCategoriaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHamburguer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBatatas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCombos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuggets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMilkShakes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBebidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCategoriaProdutosLayout.setVerticalGroup(
            panelCategoriaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriaProdutosLayout.createSequentialGroup()
                .addComponent(panelCategoriaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHamburguer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatatas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuggets, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMilkShakes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelFooter.setBackground(new java.awt.Color(181, 18, 23));
        panelFooter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblFooter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFooter.setForeground(new java.awt.Color(255, 255, 255));
        lblFooter.setText("BIT BURGUER - FEITO COM QUALIDADE - DO JEITO AMERICANO");

        btnLimparPedido.setBackground(new java.awt.Color(255, 248, 232));
        btnLimparPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimparPedido.setText("LIMPAR PEDIDO");

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFooter)
                .addGap(31, 31, 31)
                .addComponent(btnLimparPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(lblFooter))
                .addContainerGap())
        );

        panelInfoProdutos.setBackground(new java.awt.Color(255, 241, 214));
        panelInfoProdutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelEscolhaInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEscolha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEscolha.setText("ESCOLHA SEU HAMBÚRGUER PREFERIDO");

        lblTipoCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipoCategoria.setText("HAMBÚRGUER");

        javax.swing.GroupLayout panelEscolhaInfoLayout = new javax.swing.GroupLayout(panelEscolhaInfo);
        panelEscolhaInfo.setLayout(panelEscolhaInfoLayout);
        panelEscolhaInfoLayout.setHorizontalGroup(
            panelEscolhaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEscolhaInfoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblTipoCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        panelEscolhaInfoLayout.setVerticalGroup(
            panelEscolhaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscolhaInfoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelEscolhaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEscolha)
                    .addComponent(lblTipoCategoria))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblProduto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblProduto.setText("Produto:");

        comboBoxProdutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxProdutos.addActionListener(this::comboBoxProdutosActionPerformed);

        lblPreco.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPreco.setText("Preço:");

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDescricao.setText("Descrição:");

        textaAreaDescProduto.setColumns(20);
        textaAreaDescProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textaAreaDescProduto.setRows(5);
        jScrollPane1.setViewportView(textaAreaDescProduto);

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblQuantidade.setText("Quantidade:");

        txtQuantidade.setText("jTextField1");
        txtQuantidade.addActionListener(this::txtQuantidadeActionPerformed);

        btnAddPedido.setBackground(new java.awt.Color(181, 18, 23));
        btnAddPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPedido.setText("Adicionar ao Pedido");
        btnAddPedido.addActionListener(this::btnAddPedidoActionPerformed);

        btnMeuPedido.setBackground(new java.awt.Color(0, 0, 0));
        btnMeuPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMeuPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnMeuPedido.setText("Ver meu Pedido ( 0 Itens )");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblValorDoProduto.setBackground(new java.awt.Color(255, 255, 255));
        lblValorDoProduto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblValorDoProduto.setForeground(new java.awt.Color(181, 18, 23));
        lblValorDoProduto.setText("R$ 22,50");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblValorDoProduto)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValorDoProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInfoProdutosLayout = new javax.swing.GroupLayout(panelInfoProdutos);
        panelInfoProdutos.setLayout(panelInfoProdutosLayout);
        panelInfoProdutosLayout.setHorizontalGroup(
            panelInfoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscolhaInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelInfoProdutosLayout.createSequentialGroup()
                .addGroup(panelInfoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoProdutosLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelInfoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInfoProdutosLayout.createSequentialGroup()
                                .addGroup(panelInfoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelInfoProdutosLayout.createSequentialGroup()
                                        .addComponent(lblDescricao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelInfoProdutosLayout.createSequentialGroup()
                                        .addComponent(lblProduto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboBoxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPreco)
                                        .addGap(15, 15, 15)))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInfoProdutosLayout.createSequentialGroup()
                                .addComponent(lblQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))))
                    .addGroup(panelInfoProdutosLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnMeuPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelInfoProdutosLayout.setVerticalGroup(
            panelInfoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoProdutosLayout.createSequentialGroup()
                .addComponent(panelEscolhaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelInfoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoProdutosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panelInfoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPreco)
                            .addComponent(lblProduto)
                            .addComponent(comboBoxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(lblDescricao))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelInfoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQuantidade)
                        .addComponent(spinerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMeuPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelCategoriaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInfoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(panelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCategoriaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInfoProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxProdutosActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void btnAddPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPedidoActionPerformed

    private void btnBatatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatatasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatatasActionPerformed

    private void btnNuggetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuggetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuggetsActionPerformed

    private void btnMilkShakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMilkShakesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMilkShakesActionPerformed

    private void btnBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBebidasActionPerformed

    private void btnHamburguerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHamburguerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCardapio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPedido;
    private javax.swing.JButton btnBatatas;
    private javax.swing.JButton btnBebidas;
    private javax.swing.JButton btnCombos;
    private javax.swing.JButton btnHamburguer;
    private javax.swing.JButton btnLimparPedido;
    private javax.swing.JButton btnMeuPedido;
    private javax.swing.JButton btnMilkShakes;
    private javax.swing.JButton btnNuggets;
    private javax.swing.JComboBox<String> comboBoxProdutos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEscolha;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTipoCategoria;
    private javax.swing.JLabel lblValorDoProduto;
    private javax.swing.JPanel panelCategoriaProdutos;
    private javax.swing.JPanel panelCategoriaTitulo;
    private javax.swing.JPanel panelEscolhaInfo;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelInfoProdutos;
    private javax.swing.JSpinner spinerQuantidade;
    private javax.swing.JTextArea textaAreaDescProduto;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
